typography_spectrum: 0.11092027323320508
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 1
  lightness: 0.36086443858221173
  saturation: 0.9120548367500305
  rhythmicContrast: 0.9599159571807832
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75723
analytics:
  google: null
  facebook: null
  twitter: null
name: Kevin Gallagher
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: Never Loose A Sale By Automating Your Follow-up
purpose: []
